
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skpsygskqgifddhzrmde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrcHN5Z3NrcWdpZmRkaHpybWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDI4ODQsImV4cCI6MjA1NzYxODg4NH0.-KKmZ218nseNXfUv2zNYQPKL4jXoEpB8r6yk3oxQcZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
